defaults: &base
  tmdb_key:
  web_categories:
    - All
    - Action
    - Adventure
    - Comedy
    - Drama
    - Horror
    - Fantasy
    - Science Fiction
  covers:
    mid:   web/public/covers
    w154:  web/public/covers/thumb
  categories:
    decade: Decade
    director: Director
    genres: Genre
    rating: Rating
    year: Year
  create_dirs: true

development:
  <<: *base
  database: 'postgres://localhost/movmonster_dev'
  log: ./movmonster.log
  covers:
    mid:   web/public/covers
    w154:  web/public/covers/thumb
  base_dirs:
    - test/a-l
    - test/m-z
  destination_dir: test/filed

test:
  <<: *base
  database: 'postgres://localhost/movmonster_test'
  destination_dir: test/filed
  base_dirs:
    - test/a-l
    - test/m-z
  log: ./test/test.log

production:
  <<: *base
  database: 'postgres://movmonster:xxxxxxxxxx@localhost/movmonster'
  base_dirs:
    - /media/external/movies/
  destination_dir: /media/movies
