defaults: &base
  tmdb_key:
  web_categories:
    - All
    - Action
    - Adventure
    - Comedy
    - Drama
    - Horror
    - Fantasy
    - Science Fiction
  covers:
    mid:   web/public/covers
    w154:  web/public/covers/thumb
  categories:
    decade: Decade
    director: Director
    genre: Genre
    rating: Rating
    year: Year

development:
  <<: *base
  database: 'postgres://localhost/movmonster_dev'
  log: movmonster.log
  covers:
    mid:   web/public/covers
    w154:  web/public/covers/thumb
  base_dir: test/movies/All
  destination_dir: test/movies

test:
  <<: *base
  database: 'postgres://localhost/movmonster_test'
  base_dir: test/movies/All
  destination_dir: test/movies
  covers:
    mid:   test/covers
    w154:  test/covers/thumb
  log: test/test.log

production:
  <<: *base
  database: 'postgres://movmonster:xxxxxxxxxx@localhost/movmonster'
  base_dir: /home/media/movies/All
  destination_dir: /media/movies
